#!/usr/local/bin/python
# Python 2.7 Scripting for System Administrators

import argparse

parser = argparse.ArgumentParser(description='Search for words including partial word')
parser.add_argument('snippet', help='partial (or complete) string to search for in words file')

args = parser.parse_args()
snippet = args.snippet.lower()

words = open('/usr/share/dict/words').readlines()

#matches = []

#for word in words:
#  if snippet in word.lower():
#    matches.append(word)

#print(matches)

print([word.strip() for word in words if snippet in word.lower()])
