#!/usr/local/bin/python
# Python 2.7 Scripting for System Administrators

import os

# using with open means python closes the file when it's done automatically 
with open('xmen.txt') as xmen_file: # default is read only
  print(xmen_file.read())

#with open('xmen.txt', 'w') as xmen_file: # write only 
# Python 2
#xmen_file.seek(-1, os.SEEK_END)
# Python 3
#xmen_file.seek(0, os.SEEK_END)
#xmen_file.write("\nBeast\n")
#xmen_file.write("Phoenix\n")

#with open('xmen.txt', 'r+') as xmen_file: # read-write
#xmen_file.seek(-1, os.SEEK_END)
#xmen_file.write("\nBeast\n")
#xmen_file.write("Phoenix\n")

#with open('xmen.txt', 'a') as xmen_file: # append
#xmen_file.writelines(['Morph\n', 'Rogue\n'])
